import {Bitaprprescrip} from './Bitaprprescrip';
import {Bitaprespirador} from './Bitaprespirador';
import {BitaprIngresado} from './BitaprIngresado';

export interface Bitapr {
  idbitapr: string;
  nipcrea: string;
  fecha: string;
  fechaTipoDate: Date;
  ot: string;
  tag: string;
  elevacion: string;
  azimut: string;
  actividad: string;
  numpersonas: string;
  tiempo: string;
  rapexposicion: string;
  dosisestimada: string;
  dosisobtenida: string;
  petar: string;
  tarea: string;
  alarapidez: string;
  aladosis: string;
  comentarios: string;
  estado: string;
  motivocancela: string;
  prescripcionesCadena: string;
  respiradoresCadena: string;
  nip_jefeturno: string;
  nombre_jefeturno: string;
  nip_ingpr: string;
  nombre_ingpr: string;
  equipo: string;
  cuarto: string;
  kdpm: string;
  numerorec: string;
  unidad: string;
  estadooperacion: string;
  listaPrescipcion: Bitaprprescrip[];
  listaRespirador: Bitaprespirador[];
  listaIngresados: BitaprIngresado[];
  sabeUbicacion: string;
  rutaAcceso: string;
  sitioAlara: string;
  nip_custodio: string;
  nombre_custodio: string;
  nivelRadiacion: string;
  pasosCriticos: string;
  esperaRapidez: string;
  criterioParo: string;
  puntoDetencion: string; 
  exop: string;
  soer: string[]; 
  soer_cadena: string;
  fechaReporte: string;
  fechaReporteTipoDate: Date;
  nipPrCoberturaReporte: string;
  nipPrpretrabajo: string;
  nipResponsableTrabajo: string;
}
